name: context_di
description: "Flutter Provider based Dependency Injection Tool
supports two main scopes factory and singleton with code generation"
version: 0.2.5
homepage: https://github.com/begekoth/context_di
topics:
  - dependency
  - injection
  - dependency-injection
  - provider
  - flutter

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

