name: context_di_generator
description: "Flutter Provider based Dependency Injection Tool Generator"
version: 0.2.5
homepage: https://github.com/begekoth/context_di

environment:
  sdk: ^3.8.0

dependencies:

  context_di: ^0.2.5
  source_gen: '>=3.1.0 <5.0.0'
  build: '>=3.0.0 <5.0.0'
  analyzer: ">=7.4.0 <8.0.0"
