name: context_di_generator
description: "Flutter Provider based Dependency Injection Tool Generator"
version: 0.2.5
homepage: https://github.com/begekoth/context_di

environment:
  sdk: ^3.6.0

dependencies:

  context_di: ^0.2.4
  source_gen: ^3.0.0
  build_runner: ^2.7.1
  build: ^3.0.0
  analyzer: ^7.4.5
